<?php
 /*
 Template Name: MOZR Terms
 */
 get_header(); ?>
</div><!-- Content  -->
    
    <div class="container jb-mobile legal-container" style="background-image:url(<?php echo get_stylesheet_directory_uri() ?>/img/legal-hero-image.jpg)">
    
        <div class="col-md-6 mozr-page-title legal">
            <h1>
            Terms of Service
            </h1>
            
        </div>
   
    </div>
</div>

<div class="col-xs-12 post-cont">

    <div class="container margin-bottom-50">
        <div class="col-sm-4">
        <h4 class="mozr-grey-bk legal-button legal-active">Terms of Service</h4>
        <h4 linkto="service-level-agreement" class="mozr-grey-bk legal-button footer-link">Service Level Agreement</h4>
        <h4 linkto="privacy-and-copyright" class="mozr-grey-bk legal-button footer-link">Privacy and Copyright</h4>
        <h4 linkto="acceptable-use-policy" class="mozr-grey-bk legal-button footer-link">Acceptable Use Policy</h4>
        </div>
        
        <div class="col-sm-8 legal-font-size">
            <p>These Terms and Conditions, together with any terms clicked-through in the process of purchasing services (an “Order”), 
            our Service Level Agreement (“<b>SLA</b>”) located at (<a href="/service-level-agreement">http://www.mozr.com/service-level-agreement/</a>), 
            and the Acceptable Use Policy (“<b>AUP</b>”) located at (<a href="/acceptable-use-policy">http://www.mozr.com/acceptable-use-policy/</a>), 
            each of which is incorporated by reference, 
            set forth the terms and conditions pursuant to which MOZR (“we”, “us”, or “our”) will provide the Services to you (“<b>Agreement</b>”). 
            Capitalized terms used but not defined herein have the meanings ascribed to them in the Order. We may update this Agreement from time-to-time. 
            In the event of a material change to this Agreement, we will provide you with written notice. Your continued use of the Services following such updates constitutes your acceptance of the same. 
            If you do not agree to the terms of any modification, you may terminate this Agreement in accordance with the Termination section below.</p>
            <h2>CONTRACTING PARTY AND AUTHORIZED USERS</h2>
            <ul>
                <li>While signing up, you provided personal information of the account owner (“<b>Customer</b>”). The Customer is the sole owner of the account. By agreeing to these terms, you represent and warrant that you have the authority to bind Customer to this Agreement.</li>
                <li>No individual will be able to access or make changes to the account unless they are expressly designated through the customer portal (“<b>Authorized User(s)</b>”).</li>
                <li>Each person or entity that accesses your account is required to abide by the terms of this Agreement. You acknowledge that you are fully responsible for all liabilities incurred through use of the account the Services including all damages, losses and liabilities caused by each user. You shall promptly notify us in the event that you become aware of any violation of this Agreement. You are solely responsible for the security and confidentiality of the account information, including usernames and passwords, and you will ensure that no unauthorized party uses the account.</li>
            </ul>
            <h2>PROVISION AND USE OF THE SERVICES</h2>
            <ul>
                <li>You acknowledge that we may engage third parties to provide or enable elements of the Services.</li>
                <li>From time-to-time we may cease supporting aspects of the Services (any such event, an “<b>End of Life</b>”). Should components of the Services come to an End of Life, we will attempt to replace them with comparable components, but may not be able to do so. An End of Life is not a breach of this Agreement.</li>
                <li>Certain aspects of the Services may be in beta form as designated by us (“<b>Beta Services</b>”). In addition to the disclaimers of warranty set out in this Agreement, the Beta Services are provided on an as-is basis with the express understanding that they may not have been tested, have faults, and may not be as secure as other elements of the Services. Any SLA does not apply to the Beta Services. We reserve the right to terminate the Beta Services at any time, even if you have relied on them as a material inducement to enter into this Agreement. We make no guarantee that Beta Services will be put into production.</li>
                <li>While we do provide backup, there is no guarantee that the backup will work properly and that the content will be completely recovered or formatted properly. You are solely responsible for keeping a separate backup of any data that you do not want to lose.</li>
            </ul>
            <h2>SUPPORT</h2>
            <ul>
                <li>We provide support through a variety of methods (e.g. knowledgebase, forums, chat) (“Support”). Please refer to <a href="https://mozr.freshdesk.com" target="_blank">https://support.mozr.com/</a> for the most current support information.</li>
                <li>If you abuse our support staff or any employee of MOZR, we may terminate this agreement and your access to the Services effective immediately.</li>
                <li>During our interactions with you, including while providing Support, we may solicit or you may provide feedback about the Services. You agree that we are free to use and disclose this feedback for any purpose. If we make any changes to our current services or products, or develop new products or services, using the feedback, then you agree that we own all right, title and interest to such changes or new products or services.</li>
            </ul>
            <h2>FEES</h2>
            <ul>
                <li>The charges for the Services are set out on the Order (“Fees”). Fees applicable to any renewal Term will be at our then-current rates. Overages may apply if your use of the Services exceeds your plan limits (e.g. exceeding the number of monthly visitors). Additionally, we may adjust the Fees if there is a change to the configuration your sites or your use of the Services (including changes to CPU or RAM consumption, cacheability, bandwidth, visitors, or transfer).</li>
                <li>You will be charged the Fees beginning on the Effective Date. Our schedule of payments is set out on the Order; if no schedule is stated, Fees are due in full in advance, except that Fees for applicable overages will be invoiced and charged in arrears. All Fees are payable in U.S. dollars and are not refundable. We will collect the Fees by debiting the electronic payment method that you have provided to us. Credit, debit, or other similar sources of payment may be debited up to one week prior to the due date. You must keep the method of payment current and able to be debited. If payment is not made by or on the due date, we may charge a late fee on the unpaid balance at the lesser of one and one-half percent (1.5%) per month or the maximum lawful rate permitted by applicable law, rounded to the next highest whole month and compounded monthly.</li>
                <li>We may be required to collect taxes on the Services. Taxes (excluding taxes on our income) will be added to the Fees and you agree to pay them, unless you provide us with a valid tax exemption certificate. If you elect to pay via a wire transfer or credit transfer then you are responsible for any transfer fees, which will be automatically added to the Fees.</li>
                <li>If you do not pay on time, we may suspend or terminate the Services and terminate this Agreement. In addition, Third Party Services may be forfeited. We may also send you to collections, and add to the Fees any charges associated with collecting unpaid Fees. If the Services are suspended because we do not receive payment, we will preserve Customer Content (defined below) in accordance with our normal backup processes and procedures. After that time the Customer Content will be deleted.</li>
                <li>If the Order references any money-back guarantee, this guarantee applies only to our standard Services and not to Third Party Services (e.g. domain names), set up or migration Services, or other Services that are custom or non-standard.</li>
            </ul>
            <h2>MIGRATIONS</h2>
            <ul>
                <li>By agreeing to migrate your website to MOZR, you understand that you will be redirected to third party websites to acquire and utilize third party products, including plugins, and services that are not owned or controlled by MOZR. MOZR has no responsibility for the terms of use or service, privacy policies, or practices of any such third party provider. Your use of any such third party provider for migration purposes is at your own risk, and you expressly release MOZR from any and all liability arising from your use of the same.</li>
            </ul>
            <h2>PROPRIETARY RIGHTS</h2>
            <ul>
                <li>We do not claim any ownership rights in your content that you provide to us in connection with the Services (“<b>Customer Content</b>“). </li>
                <li>MOZR and its licensors own all right, title, and interest in and to Services and the systems and networks used to provide such Services (including all system generated data (e.g. performance data)), including all modifications, improvements, upgrades, derivative works, and feedback provided by you or any Authorized User and all intellectual property rights in and to any of the foregoing. You agree to assign all right, title, and interest you may have in the foregoing to us. Except for the express rights granted herein, we do not grant any other licenses, whether express or implied, to any of MOZR’s intellectual property including software, services and products.</li>
            </ul>
            <h2>TERM AND TERMINATION</h2>
            <ul>
                <li>The term of this Agreement and any Order is one-month starting from the date Customer signs up (“<b>Initial Term</b>”). Upon expiration of the Initial Term, this Agreement and any Order automatically renew for successive one month periods (each a “<b>Renewal Term</b>”) unless one party notifies the other in writing of its intent not to renew no later than thirty days prior to the expiration of the then-current Renewal Term or the Agreement or Order is otherwise terminated in accordance with the terms of this Agreement.</li>
                <li>Either party may terminate this Agreement and any Order at any time for any reason at any time for any reason or no reason by providing the other party with 30 days’ prior written notice. Additionally, we may terminate this Agreement or any Order immediately if (i) you fail to pay for Services on time, (ii) your use of the Services endangers or negatively affects our networks or systems, violates the law or our AUP, or inhibits our ability to provide services to our other customers.</li>
                <li>Upon any termination or expiration of this Agreement we will stop providing the Services. This means that Customer’s Content may not be available. It is Customer’s sole obligation to keep separate backups and to download the Customer Content prior to termination or the expiration this Agreement.</li>
            </ul>
            <h2>CONFIDENTIALITY</h2>
            <ul>
                <li>“<b>Confidential Information</b>” means any information disclosed by us to you, either directly or indirectly, in writing, orally, or by inspection of tangible objects (i) that we identify as confidential or proprietary; or (ii) that reasonably appears to be confidential or proprietary because of legends or other markings, the circumstances of disclosure, or the nature of the information itself. You agree to preserve the confidential nature of the our Confidential Information by retaining and using the Confidential Information in trust and confidence, solely for its use as permitted and in connection with this Agreement. We will have the right to seek an injunction (without having to post a bond) to prevent any breach or continued breach of this section. You agree to promptly report any breaches of this section to us.</li>
            </ul>
            <h2>WARRANTIES</h2>
            <ul>
                <li>Each party represents and warrants that it has the power, authority and legal right to enter into this Agreement and to perform the obligations set out in it, and those set out in contracts incorporated by reference.</li>
                <li>Customer represents and warrants that it owns or has a license for all intellectual property and other proprietary rights necessary to make the license grants to us contained herein. At our request, Customer will provide us evidence of this ownership or license. Customer represents and warrants that our use of the Customer Content in accordance with such license will not infringe the intellectual property or other proprietary rights of any individual or entity. Customer also represents and warrants that all information it provides to us is complete, accurate and up-to-date. Finally, Customer represents and warrants that if it is a natural person, that it is over eighteen years of age.</li>
            </ul>
            <h2>DISCLAIMER</h2>
            <ul>
                <li>OTHER THAN AS IS EXPRESSLY SET OUT IN THE SLA, THE SERVICES ARE PROVIDED AS-IS, AS AVAILABLE, AND WITH ALL FAULTS. EXCEPT AS EXPRESSLY PROVIDED IN THE WARRANTIES SECTION, ABOVE, (i) MOZR MAKES NO WARRANTIES OF ANY KIND, WHETHER EXPRESS, IMPLIED, STATUTORY OR OTHERWISE, AND (ii) MOZR AND ITS LICENSORS SPECIFICALLY DISCLAIM ALL IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO: ANY WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, UNINTERRUPTED OR ERROR FREE SERVICE, ERROR CORRECTION, AVAILABILITY, ACCURACY AND ANY AND ALL IMPLIED WARRANTIES ARISING FROM STATUTE, COURSE OF DEALING, COURSE OF PERFORMANCE OR USAGE OF TRADE TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW.</li>
            </ul>
            <h2>LIMITATION OF LIABILITY AND REMEDIES</h2>
            <ul>
                <li>IN NO EVENT SHALL OUR LIABILITY ARISING OUT OF, OR RELATED TO, THIS AGREEMENT, FOR ANY REASON, INCLUDING, BUT NOT LIMITED TO, CONTRACT, TORT OR UNDER ANY OTHER THEORY OF LIABILITY, EXCEED IN THE AGGREGATE AMOUNT OF FEES PAID OR OWED BY CUSTOMER TO US IN THE THREE MONTHS PRECEDING THE CLAIM.</li>
                <li>IN NO EVENT SHALL WE OR OUR LICENSORS HAVE ANY LIABILITY TO CUSTOMER FOR ANY INDIRECT, SPECIAL, INCIDENTAL, CONSEQUENTIAL, COVER OR PUNITIVE DAMAGES HOWEVER CAUSED, ARISING OUT OF, OR IN ANY WAY CONNECTED WITH, THE SERVICES, INCLUDING, BUT NOT LIMITED TO, THE USE, OR INABILITY TO USE, THE SERVICES OR FOR ANY CONTENT, OR ANY INTERRUPTION IN THE SERVICES, WHETHER IN CONTRACT, TORT OR UNDER ANY OTHER THEORY OF LIABILITY, AND WHETHER OR NOT THE PARTY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.</li>
                <li>CUSTOMER AGREES THAT OUR SLA CONTAINS CUSTOMER’S SOLE AND EXCLUSIVE REMEDY FOR INTERRUPTION, PARTIAL UNAVAILABILITY, AND COMPLETE UNAVAILABILITY OF THE SERVICES, AND ANY OTHER ITEM SET OUT IN THE SLA.</li>
                <li>THE DISCLAIMERS AND LIMITATIONS PROVIDED HEREIN DO NOT APPLY TO THE EXTENT PROHIBITED BY APPLICABLE LAW.</li>
            </ul>
            <h2>INDEMNIFICATION</h2>
            <ul>
                <li>You agree to defend us against any claim, demand, suit or proceeding made or brought against us by a third party arising out of your conduct that constitutes a violation of our Authorized Use Policy. Customer will indemnify us for damages finally awarded against us in connection with any such claim (or for a settlement amount Customer consents to).</li>
            </ul>
            <h2>SECURITY; SAFE HARBOR</h2>
            <ul>
                <li>We will maintain commercially reasonable administrative, physical and technical safeguards designed to help ensure the security of our internal networks from malicious activity and to provide for the privacy, confidentiality and integrity thereof. However, security is a shared responsibility. You agree to configure your use of the Services in such a way as to maintain the security of our Services and network (e.g. by only uploading software that has been demonstrated to be secure, installing patches, and not sharing passwords).</li>
                <li>Should we determine that there has been a security breach that has compromised your account we agree to notify you as soon as reasonably possible but only after we have investigated the breach and fulfilled our legal obligations under applicable law. You agree to the same notification obligations should you determine that there has been a breach.</li>
                <li>Data Controller/Data Processor. This section applies only to customers that are located in a European Economic Area member state. We are the data controller for the personal data those customers submit through the sign up process (e.g. contact information, credit card number). For all other personal data collected through provision of the Services (i.e. any personal data submitted through supported sites), we are the data processor. Where we are the data processor, we will endeavor to use such personal data only as instructed by the customer and not for any other purposes.</li>
            </ul>
            <h2>GENERAL PROVISIONS</h2>
            <ul>
                <li><i>Publicity</i>. Upon our written request, the parties will cooperate on and issue a press release, provided that neither party may do so without providing the other party a reasonable opportunity for input. During the term, either party may include the name and logo of the other party in lists of customers or vendors in accordance with the other party’s standard trademark usage guidelines. You will allow our public relations agencies or in-house staff to interview, write, and place case studies and written endorsements in initial news, reviews, and editorial calendar opportunities. You also agree to participate in phone interviews with prospective customers and investors, industry analysts, and review and news editors as requested by from time to time.</li>
                <li><i>Governing Law and Venue</i>. This Agreement is governed by the laws of the State of Texas, without regard to its choice of law statutes. Any disputes must be brought in the <u>U.S. District Court for the Western District of Texas</u>, located in <u>Austin, Texas</u>. If that U.S. District Court cannot hear the dispute, the dispute shall be brought before the <u>State District Courts of Travis County located in Austin, Texas</u>. The parties agree that venue and jurisdiction is proper in this court and agree not to contest notice from this court. The United Nations Convention on the International Sale of Goods is disclaimed. <b>EACH PARTY WAIVES ANY RIGHT TO JURY TRIAL IN CONNECTION WITH ANY ACTION OR LITIGATION IN ANY WAY RISING OUT OF, OR RELATED TO, THIS AGREEMENT</b>. The parties further agree that the pricing and terms of this Agreement were made in reliance upon agreement to this paragraph.</li>
                <li><b>ARBITRATION AND CLASS ACTION WAIVER.</b> Both parties agree that, except as otherwise provided herein, all disputes (including any dispute involving interpretation, applicability, enforceability, or formation of the Agreement, including any claim that the Agreement or any part of it is void or voidable)will be resolved by binding, individual arbitration under the American Arbitration Association’s rules. Both parties waive trial by jury. As an alternative, either party may bring a claim in Customer’s local “small claims” court if permitted by that court’s rules. Additionally, either party may seek emergency injunctive relief by filing for such in accordance with the Governing Law and Venue section above. Customer may bring claims only on its own behalf. Neither party may participate in a class action or class-wide arbitration for any claims covered by this Agreement. Customer also agrees not to participate in claims brought in a private attorney general or representative capacity, or consolidated claims involving another person’s account, if we are a party to the proceeding. This dispute resolution provision will be governed by the Federal Arbitration Act. In the event the American Arbitration Association is unwilling or unable to set a hearing date within one hundred and sixty (160) days of filing the case, then either party may elect to have the arbitration administered instead by the Judicial Arbitration and Mediation Services. Judgment on the award rendered by the arbitrator may be entered in any court having competent jurisdiction. Any provision of applicable law notwithstanding, the arbitrator will not have authority to award damages, remedies or awards that conflict with this Agreement. MOZR will pay all arbitration fees (excluding attorneys’ fees) for claims less than $10,000. MOZR will not seek its attorneys’ fees and costs in arbitration unless the arbitrator determines that your claim is frivolous.</li>
                <li><b>You may opt out of this agreement to arbitrate.</b> If Customer does opt out, neither party can require the other to participate in an arbitration proceeding. To opt out, Customer must notify us in writing, via the following email or mail address, within thirty (30) days of the date that Customer first became subject to this arbitration provision: <i>MOZR, LLC. ATTN: LEGAL – Arbitration Opt-Out, 563 S 600 W Mapleton, UT 84664; and/or, legal@mozr.com</i>. Customer must include their name, residence address, and a clear statement that Customer wants to opt out of this arbitration agreement. If the prohibition against class actions and other claims brought on behalf of third parties or arbitration clause contained above is found to be unenforceable or if Customer opts-out of arbitration then all of the preceding language in this section will be null and void and the Governing Law and Venue section shall control. This arbitration agreement will survive the termination of Customer’s relationship with us. The parties further agree that the pricing and terms of this Agreement were made in reliance upon agreement to this paragraph.</li>
                <li><i>Amendment and Waiver</i>. Except as expressly provided herein, this Agreement, including any other contracts incorporated by reference, may only be amended as agreed by the parties in a written amendment (including by a click-to-accept that is accepted by you or Authorized User). The parties further agree that upgrades (e.g. moving up a service plan level), downgrades (e.g. moving down a service plan level), and additional services (e.g. adding account management services) may be agreed via electronic communication (e.g. ticket or email) that is acknowledged by authorized representatives for both parties. If one party fails to exercise, or delays exercising, any right, remedy or power set out in this Agreement, this will not operate as a waiver of that right, remedy or power, whether under this Agreement or at law or equity.</li>
                <li><i>Assignment</i>. Neither party may assign this Agreement, in whole or in part, without the other party’s prior written consent, provided that no consent is required in connection with a merger, reorganization, sale of assets or similar transaction. Any purported assignment in violation of this section shall be null and void. The Agreement will be binding on all permitted successors and assigns</li>
                <li><i>Severability</i>. Any provision in this Agreement that is held to be illegal or unenforceable in any jurisdiction will be effective only up to the extent of such illegality or unenforceability, if possible, and will not invalidate the remaining provisions of the paragraph or this Agreement. To the largest extent possible, the illegal or unenforceable provision will be restated to reflect the parties’ intent.</li>
                <li><i>Entire Agreement</i>. This Agreement, and any document incorporated by reference, states the entire agreement between the parties with respect to the subject matter and supersedes all previous proposals, negotiations and other written or oral communications between the parties. Customer’s pre-printed purchase orders will have no force or effect.</li>
                <li><i>Order of Precedence</i>. If there is a conflict between this Agreement and any contracts incorporated by reference, they shall have the following precedence: Order, Agreement, then the applicable exhibit or other referenced document.</li>
                <li><i>Force Majeure</i>. We shall not be deemed to be in default of this Agreement, or to have breached any of its provisions, as a result of a delay, failure in performance, or interruption in the Services which result, either directly or indirectly, from any circumstances beyond our reasonable control including acts of god, acts of civil or military authority, civil disturbance, war, strikes, fire, laws, regulations, governmental acts, third party network unavailability, and/or failure of telecommunication facilities.</li>
                <li><i>Third Party Beneficiaries; Relationship</i>. There are no third party beneficiaries to this Agreement. Nothing contained in this Agreement will be deemed or construed as creating a joint venture or partnership. No party is by virtue of this Agreement authorized as an agent, employee or legal representative of any other party. Neither party has the authority to make any representations, claims or warranties of any kind on behalf of the other party, nor on behalf of that party’s affiliates, agents, subcontractors, licensors or third-party suppliers.</li>
                <li><i>Notices</i>. Except as otherwise required herein, notices shall be effective when delivered, as indicated by a delivery receipt, or, in the case of notices delivered by post, five business days after being mailed to the designated address by first class mail. Notices to you may be made to the address set out in our customer record or electronically, through the Customer’s portal or via email to an Authorized User. You will send all notices to us at the following address: MOZR 563 S 600 W, Mapleton, UT 84664.</li>
                <li><i>Survival</i>. Any provision of this Agreement that contemplates performance or observance subsequent to termination or expiration of this Agreement (including, without limitation, confidentiality, limitation of liability and indemnification) will survive termination or expiration and continue in full force and effect.</li>
            </ul>
        </div>
    </div>

</div>

<div class=""> <!-- row -->
   <div id="content" class="container">
<?php
 get_footer();